import { LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, Legend, ResponsiveContainer } from "recharts";
import { TrendingUp } from "lucide-react";
import { formatCurrency, formatCurrencyFull } from "./formatters";

export function FinancialTrendChart({ data = [] }) {
    return <section id="tren" className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-start gap-3"><div className="rounded-lg bg-blue-50 p-2 text-blue-600"><TrendingUp className="h-5 w-5" /></div><div><h2 className="text-base font-semibold text-slate-900">Grafik Tren Total Akun</h2><p className="mt-1 text-sm text-slate-500">Maksimal lima periode terakhir dengan jenis yang sama, hingga periode yang dipilih.</p></div></div>{data.length < 2 ? <div className="mt-6 flex h-64 items-center justify-center rounded-lg border border-dashed border-slate-200 bg-slate-50 text-sm text-slate-500">Minimal dua periode sejenis diperlukan untuk menampilkan tren.</div> : <div className="mt-6 grid gap-8 xl:grid-cols-2"><TrendPanel title="Laba Rugi" description="Pendapatan dan laba bersih dari Laba Rugi." data={data} lines={[{ key: "revenue", label: "Pendapatan", color: "#2563eb" }, { key: "totalExpenses", label: "Total Beban", color: "#059669" }]} /><TrendPanel title="Neraca" description="Aset, kas, liabilitas, dan ekuitas dari Neraca." data={data} lines={[{ key: "totalAssets", label: "Total Aset", color: "#4f46e5" }, { key: "cash", label: "Kas", color: "#06b6d4" }, { key: "totalLiabilities", label: "Total Liabilitas", color: "#dc2626" }, { key: "equity", label: "Ekuitas", color: "#d97706" }]} /></div>}</section>;
}

function TrendPanel({ title, description, data, lines }) {
    return <div><div><h3 className="text-sm font-semibold text-slate-800">{title}</h3><p className="mt-1 text-xs text-slate-500">{description}</p></div><div className="mt-4 h-64"><ResponsiveContainer width="100%" height="100%"><LineChart data={data} margin={{ top: 8, right: 18, left: 0, bottom: 0 }}><CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" vertical={false} /><XAxis dataKey="label" tick={{ fontSize: 12, fill: "#64748b" }} axisLine={false} tickLine={false} /><YAxis tickFormatter={formatCurrency} tick={{ fontSize: 11, fill: "#64748b" }} axisLine={false} tickLine={false} width={72} /><Tooltip formatter={(value) => formatCurrencyFull(value)} contentStyle={{ borderRadius: 10, border: "1px solid #e2e8f0", fontSize: 12 }} /><Legend wrapperStyle={{ fontSize: 12, paddingTop: 12 }} />{lines.map((line) => <Line key={line.key} type="monotone" dataKey={line.key} name={line.label} stroke={line.color} strokeWidth={2.5} dot={{ r: 3 }} activeDot={{ r: 5 }} connectNulls={false} />)}</LineChart></ResponsiveContainer></div></div>;
}
